### ISSUE TITLE
Error when running scan

### ISSUE THREAD

**Issue by frg100** [fluidattacks/makes#1071]
Recently while following the following instructions

https://appdefensealliance.dev/casa/tier-2/ast-guide/static-scan

I'm getting the following error:

```
─────────────────────────────────── Running ────────────────────────────────────
[WARNING] Function: __main__.cli_scan_wrapped, type: Some keys were not recognized: path
Traceback (most recent call last):
  File "/nix/store/jn52wllfm0v0kyx948n4aj8n0jgbqby4-skims/utils/function.py", line 193, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jn52wllfm0v0kyx948n4aj8n0jgbqby4-skims/cli/__init__.py", line 118, in cli_scan_wrapped
    success: bool = run(
                    ^^^^
  File "/nix/store/mw62irkbxfqm04iaqi9kdy83vb7i8i53-skims-runtime/lib/python3.11/site-packages/aioextensions/__init__.py", line 292, in run
    return asyncio.run(coroutine, debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/frj6ibpd5478z92x39vb1hz3g2gryl79-python3-3.11.2/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/nix/store/frj6ibpd5478z92x39vb1hz3g2gryl79-python3-3.11.2/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/frj6ibpd5478z92x39vb1hz3g2gryl79-python3-3.11.2/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/nix/store/jn52wllfm0v0kyx948n4aj8n0jgbqby4-skims/core/scan.py", line 227, in main
    load(group, config)  # NOSONAR
    ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jn52wllfm0v0kyx948n4aj8n0jgbqby4-skims/config/__init__.py", line 140, in load
    raise confuse.ConfigError(
confuse.exceptions.ConfigError: Some keys were not recognized: path

[INFO] Success: False
```
This worked for me a bit over a week ago, but now I'm getting the error. Would appreciate some help!

**Comment by drestrepom** [comment]
you could try to add the following keys in your configuration

```yaml
sast:
  include: []
```

this is the documentation https://docs.fluidattacks.com/machine/scanner/standalone/configuration/

**Comment by peztoa** [comment]
Yes using sast instead of path is the solution, CASA needs to update their docs

sast:
  include:
    - .
