### ISSUE TITLE
Error when scanning: KeyError: 'label_type'

### ISSUE THREAD

**Issue by lesiki** [fluidattacks/makes#1085]
I'm using [the CASA instructions](https://appdefensealliance.dev/casa/tier-2/ast-guide/static-scan) to run the scans via their dockerfile, with the following changes:
- Change configuration to use `sast` as mentioned in #1071  
- Tested with both the 22.09 and 23.04 releases, but I get the same behaviour either way

The scan goes through all paths, but then I get the error below. Note: none of these paths are from my app.

```
[WARNING] Function: __main__.cli_scan_wrapped, type: 'label_type'
Traceback (most recent call last):
  File "/nix/store/lbi9s3dn5h9l763q2hq50l3ihyvzdrqx-skims/utils/function.py", line 377, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lbi9s3dn5h9l763q2hq50l3ihyvzdrqx-skims/cli/__init__.py", line 135, in cli_scan_wrapped
    success: tuple[bool, int] = run(
                                ^^^^
  File "/nix/store/6jdy9fqfhmmy8gb9yymjf30clbh146k9-skims-runtime/lib/python3.11/site-packages/aioextensions/__init__.py", line 292, in run
    return asyncio.run(coroutine, debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/hx2c957wpwa6i3fz0wiwhg72sfgq62k1-python3-3.11.2/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/nix/store/hx2c957wpwa6i3fz0wiwhg72sfgq62k1-python3-3.11.2/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/hx2c957wpwa6i3fz0wiwhg72sfgq62k1-python3-3.11.2/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/nix/store/lbi9s3dn5h9l763q2hq50l3ihyvzdrqx-skims/core/scan.py", line 275, in main
    stores = await execute_skims()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lbi9s3dn5h9l763q2hq50l3ihyvzdrqx-skims/core/scan.py", line 101, in execute_skims
    analyze_sast(stores=stores)
  File "/nix/store/lbi9s3dn5h9l763q2hq50l3ihyvzdrqx-skims/lib_sast/analyze.py", line 34, in analyze
    analyze_root(paths=paths, stores=stores)
  File "/nix/store/lbi9s3dn5h9l763q2hq50l3ihyvzdrqx-skims/lib_root/analyze.py", line 303, in analyze
    futures = get_futures_new_architecture(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lbi9s3dn5h9l763q2hq50l3ihyvzdrqx-skims/lib_root/analyze.py", line 328, in get_futures_new_architecture
    for label, nodes in nodes_by_type(shard.syntax_graph).items():
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lbi9s3dn5h9l763q2hq50l3ihyvzdrqx-skims/utils/graph/__init__.py", line 880, in nodes_by_type
    if (label_type := graph.nodes[node]["label_type"]) not in result:
                      ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'label_type'

[INFO] Summary: An error ocurred while trying to analyze your targets.
[ERROR] Exit code: 1.

────────────────────────── 👀 Failed with exit code 1 ──────────────────────────
```

**Comment by alejolagosm** [comment]
We have made a small refactor in the code to avoid this error (See commit: https://gitlab.com/fluidattacks/universe/-/commit/a67627840d664fb5a9d6c808612377a6029cd1af)
However, this is very unexpected and we have not been able to replicate it. 
It would be very useful to us if you could share the file where this is happening, to get to the bottom of the problem please.
If not, anyway, you should now be able to run the scanner without this problem.

Thanks for using the tool!

**Comment by lesiki** [comment]
Thanks @alejolagosm , that latest change fixed it.

Happy to help in debugging, but I'm not sure which file caused this - the logs indicated that all my source files had been scanned, then I get the error after that.

Let me know if there's some verbose logging I could add to identify the file causing this?
