### ISSUE TITLE
KeyError: '32' when running a skims scan

### ISSUE THREAD

**Issue by divyanshusharma1709** [fluidattacks/makes#984]
Hello! I have run a skims scan on my project. I am using Docker on Windows 11. However, it ends with the following error:

`KeyError: '32'`

**Error log:**

```
[ERROR] '32'
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/nix/store/mbsng5p51yxdpkf53v91i6ck8fdg4w9b-python3-3.8.13/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/nix/store/2f4g00km4sbgnf1668fsvlzaskg4pjzs-skims/lib_root/f211/javascript.py", line 47, in regex_injection
    return get_vulnerabilities_from_n_ids(
  File "/nix/store/2f4g00km4sbgnf1668fsvlzaskg4pjzs-skims/sast/query.py", line 125, in get_vulnerabilities_from_n_ids
    return tuple(
  File "/nix/store/2f4g00km4sbgnf1668fsvlzaskg4pjzs-skims/sast/query.py", line 125, in <genexpr>
    return tuple(
  File "/nix/store/2f4g00km4sbgnf1668fsvlzaskg4pjzs-skims/lib_root/f211/javascript.py", line 44, in n_ids
    if is_argument_vuln(graph, n_id, method):
  File "/nix/store/2f4g00km4sbgnf1668fsvlzaskg4pjzs-skims/lib_root/f211/common.py", line 24, in is_argument_vuln
    evaluation = evaluate(method, graph, path, n_id)
  File "/nix/store/2f4g00km4sbgnf1668fsvlzaskg4pjzs-skims/symbolic_eval/evaluate.py", line 142, in evaluate
    return generic(
  File "/nix/store/2f4g00km4sbgnf1668fsvlzaskg4pjzs-skims/symbolic_eval/evaluate.py", line 130, in generic
    return evaluator(args)
  File "/nix/store/2f4g00km4sbgnf1668fsvlzaskg4pjzs-skims/symbolic_eval/cases/method_invocation.py", line 157, in evaluate
    d_expression = evaluate_method_expression(
  File "/nix/store/2f4g00km4sbgnf1668fsvlzaskg4pjzs-skims/symbolic_eval/cases/method_invocation.py", line 112, in evaluate_method_expression
    if args.graph.nodes[expr_id].get("symbol") in MODIFYING_METHODS:
  File "/nix/store/z7nyrfrrazvymg3ms6q6mdfkxjd1qbr8-skims-runtime/lib/python3.8/site-packages/networkx/classes/reportviews.py", line 187, in __getitem__
    return self._nodes[n]
KeyError: '32'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/z7nyrfrrazvymg3ms6q6mdfkxjd1qbr8-skims-runtime/lib/python3.8/site-packages/reactivex/observable/fromfuture.py", line 28, in done
    value: Any = future.result()
  File "/nix/store/mbsng5p51yxdpkf53v91i6ck8fdg4w9b-python3-3.8.13/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/nix/store/mbsng5p51yxdpkf53v91i6ck8fdg4w9b-python3-3.8.13/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
KeyError: '32'
[INFO] An output file has been written: /usr/scan/Fluid-Attacks-Results.csv
[INFO] Value missing to add:
...

[INFO] Success: True
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/nix/store/mbsng5p51yxdpkf53v91i6ck8fdg4w9b-python3-3.8.13/lib/python3.8/concurrent/futures/process.py", line 102, in _python_exit
    thread_wakeup.wakeup()
  File "/nix/store/mbsng5p51yxdpkf53v91i6ck8fdg4w9b-python3-3.8.13/lib/python3.8/concurrent/futures/process.py", line 90, in wakeup
    self._writer.send_bytes(b"")
  File "/nix/store/mbsng5p51yxdpkf53v91i6ck8fdg4w9b-python3-3.8.13/lib/python3.8/multiprocessing/connection.py", line 183, in send_bytes
    self._check_closed()
  File "/nix/store/mbsng5p51yxdpkf53v91i6ck8fdg4w9b-python3-3.8.13/lib/python3.8/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
```

Any help would be appreciated!

**Comment by danmur97** [comment]
This is not a `makes` specific issue, skims belongs to the [universe](https://gitlab.com/fluidattacks/universe) repository. Instead, see the [associated issue](https://gitlab.com/fluidattacks/universe/-/issues/8457) for this bug.
